# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/upyog-demo\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:842676012585:key/cef4af4f-7940-4480-a9ee-5c9e0f0b74d7'
